### ISSUE TITLE
Creating a policy to use with Authorization

### ISSUE THREAD

**Issue by AndyEdmonds** [littlesmilelove/graphql-authorization-aspnetcore#1]
Hi, thanks for making this.

One thing left out of the documentation is how to create a policy.  
```
           services.AddAuthorization(options =>
            {
                options.AddPolicy("AdminPolicy", policy =>
                    policy.RequireRole("Admin"));
            });
```
The above placed in Startup.cs ConfigureServices is an example of how to create one.

**Comment by littlesmilelove** [comment]
@AndyEdmonds  Thanks for your feedback. I will add it to the document.
