### ISSUE TITLE
InvalidOperationException: Cannot consume scoped service 'Microsoft.AspNetCore.Identity.UserManager'

### ISSUE THREAD

**Issue by Schwefelhexa** [littlesmilelove/graphql-authorization-aspnetcore#2]
I tried using your library together with [GraphQL.Server.Transports.AspNetCore](https://github.com/graphql-dotnet/server).
When accessing the GrapQL endpoint, I get ```InvalidOperationException: Cannot consume scoped service 'Microsoft.AspNetCore.Identity.UserManager`1[CUSTOM_USER_CLASS]' from singleton 'GraphQL.Authorization.AspNetCore.IAuthorizationEvaluator'.```

Startup.cs (`ConfigureServices`):
```C#
services.AddGraphQLAuth();
services.AddScoped<IDependencyResolver>(s => new FuncDependencyResolver(s.GetRequiredService));
services.AddScoped<AppSchema>();
services.AddGraphQL(o => { o.ExposeExceptions = false; })
    .AddGraphTypes(ServiceLifetime.Scoped)
    .AddUserContextBuilder(context => new GraphQLUserContext { User = context.User } );

services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
```

Startup.cs (`Configure`):
```C#
app.UseGraphQL<AppSchema>();
app.UseGraphQLPlayground(options: new GraphQLPlaygroundOptions());
```

My policies are generated using an Excel sheet, so I don't think showing that code is necessary. The `AuthorizationHandler` i wrote for these policies is never triggered.

**Comment by littlesmilelove** [comment]
@Schwefelhexa This exception is caused by dependency injection. Because `IAuthorizationEvaluator` is inject by `singleton lifetime`
```csharp
services.TryAddSingleton<IAuthorizationEvaluator, AuthorizationEvaluator>();
```
and `AuthorizationEvaluator`  define is
```csharp
public class AuthorizationEvaluator : IAuthorizationEvaluator
    {
        IAuthorizationService _authorizationService;
        public AuthorizationEvaluator(IAuthorizationService authorizationService)
        {
            _authorizationService = authorizationService;
        }
}
```
So, I think you redefine `IAuthorizationService ` and depent on `UserManager`, but your `UserManager` is inject as `scope lifetime`, the the dependency injection can not resolve it.

You can change your  `UserManager` life time to singleton or simply fork this repo, change the  `IAuthorizationEvaluator`  lifetime to scope.
```csharp
services.TryAddScoped<IAuthorizationEvaluator, AuthorizationEvaluator>();
```

**Comment by Schwefelhexa** [comment]
Thanks, that did solve the problem!
I've made a pull request - if it doesn't mess up anything else (which it didn't for me), maybe consider merging it?

**Comment by littlesmilelove** [comment]
@Schwefelhexa I am very happy that this can solve your problem. Thanks for your pull request.
